config/routes.rb
AdminRRHH::Application.routes.draw do
  resources :concepts

  resources :types

  resources :periods

  resources :entities

  resources :contracts

  resources :people

  resources :companies

  root :to => 'people#index'
  
end

app/models/concept.rb
class Concept < ActiveRecord::Base
end

app/controllers/concepts_controller.rb
class ConceptsController < ApplicationController
  # GET /concepts
  # GET /concepts.json
  def index
    @concepts = Concept.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @concepts }
    end
  end

  # GET /concepts/1
  # GET /concepts/1.json
  def show
    @concept = Concept.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @concept }
    end
  end

  # GET /concepts/new
  # GET /concepts/new.json
  def new
    @concept = Concept.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @concept }
    end
  end

  # GET /concepts/1/edit
  def edit
    @concept = Concept.find(params[:id])
  end

  # POST /concepts
  # POST /concepts.json
  def create
    @concept = Concept.new(params[:concept])

    respond_to do |format|
      if @concept.save
        format.html { redirect_to @concept, notice: 'Concept was successfully created.' }
        format.json { render json: @concept, status: :created, location: @concept }
      else
        format.html { render action: "new" }
        format.json { render json: @concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /concepts/1
  # PUT /concepts/1.json
  def update
    @concept = Concept.find(params[:id])

    respond_to do |format|
      if @concept.update_attributes(params[:concept])
        format.html { redirect_to @concept, notice: 'Concept was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concepts/1
  # DELETE /concepts/1.json
  def destroy
    @concept = Concept.find(params[:id])
    @concept.destroy

    respond_to do |format|
      format.html { redirect_to concepts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/views/concepts/_form.html.erb
<%= form_for(@concept) do |f| %>
  <% if @concept.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@concept.errors.count, "error") %> prohibited this concept from being saved:</h2>

      <ul>
      <% @concept.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <form>
      <fieldset>
        <div class="clearfix">
          <%= f.label :Código %>
          <div class="input">
            <%= f.text_field :code %>
          </div>  
        </div>
        <div class="clearfix">
          <%= f.label :Nombre %>
          <div class="input">
            <%= f.text_field :name %>
          </div>
        </div>
        <div class="clearfix">
          <%= f.label :Abreviatura %>
          <div class="input">
            <%= f.text_field :mininame %>
          </div>
        </div>
        <div class="clearfix">
          <%= f.label :Estado %>
          <div class="input">
            <%= f.check_box :status %>
          </div>
        </div>
        <div class="clearfix">
          <div class="input">
            <%= f.submit %>
          </div>
        </div>
      </fieldset>
  </form>
<% end %>

app/views/concepts/edit.html.erb
<h2>Editando concepto</h2>

<%= render 'form' %>

<%= link_to 'Mostrar', @concept %> |
<%= link_to 'Atrás', concepts_path %>

app/views/concepts/index.html.erb
<h2>Listando conceptos</h2>

<table  class="zebra-striped">
  <tr>
    <th>Código</th>
    <th>Nombre</th>
    <th>Abreviatura</th>
    <th>Estado</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @concepts.each do |concept| %>
  <tr>
    <td><%= concept.code %></td>
    <td><%= concept.name %></td>
    <td><%= concept.mininame %></td>
    <td><%= concept.status %></td>
    <td><%= link_to 'Show', concept %></td>
    <td><%= link_to 'Edit', edit_concept_path(concept) %></td>
    <td><%= link_to 'Destroy', concept, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Concept', new_concept_path %>

app/views/concepts/new.html.erb
<h1>New concept</h1>

<%= render 'form' %>

<%= link_to 'Back', concepts_path %>

app/views/concepts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @concept.code %>
</p>

<p>
  <b>Name:</b>
  <%= @concept.name %>
</p>

<p>
  <b>Mininame:</b>
  <%= @concept.mininame %>
</p>

<p>
  <b>Status:</b>
  <%= @concept.status %>
</p>


<%= link_to 'Edit', edit_concept_path(@concept) %> |
<%= link_to 'Back', concepts_path %>